project:
  name: quickstart-cisco-secure-firewall-cloud-native
  regions:
    - us-east-1
    - us-east-2
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    KeyPairName: override
tests:
  new-vpc:
    template: templates/entrypoint-new-vpc.template.yaml
