//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a Partner account. If there are none leave this file empty.

== Predeployment steps

=== Prepare your AWS account

To use a custom IAM policy to deploy the CloudFormation stack instead of the `AdminstratorAccess` managed policy, refer to link:#_custom_iam_policy_for_cloudformation_users[Custom IAM policy for CloudFormation users] later in this guide.

=== Prepare your {partner-company-name} account

Obtain a Cisco SFCN license from your Cisco accounts team and add it to your https://www.cisco.com/c/en/us/buy/licensing.html[Cisco smart account^]. You can deploy this Quick Start without a Cisco SFNC license with a single enforcement point at 100 Kbps throughput. For more information, refer to https://www.cisco.com/c/en/us/td/docs/security/secure-firewall/cloud-native/getting-started/secure-firewall-cloud-native-gsg/sfcn-licensing.html[Licensing^].

=== Prepare for the deployment

* Create At least one Amazon EC2 key pair: Ensure that at least one Amazon EC2 key pair exists in your AWS account in the Region where you plan to deploy the Secure Firewall Cloud Native RA-VPN solution. Make note of the key pair name. You need it to create a secret to allow the cluster to pull down files from your Amazon Simple Storage Service (Amazon S3) bucket. For more information, refer to https://www.cisco.com/c/en/us/td/docs/security/secure-firewall/cloud-native/getting-started/secure-firewall-cloud-native-gsg/sfcn-aws.html#Cisco_Task.dita_7f6b3cc2-4435-493c-8100-c5f31923612f[Create a Key Pair^].
* Download AnyConnect Secure Mobility Client v4.x for your operating system from the https://software.cisco.com/download/home/286281283/type/282364313/release/[Cisco Software Download portal^]. Version 4.8 or higher is recommended.
*** `anyconnect-linux64-4.10.04071-webdeploy-k9.pkg`
*** `anyconnect-win-4.10.04071-webdeploy-k9.pkg`
*** `anyconnect-macos-4.10.04071-webdeploy-k9.pkg`
* Create one or more AnyConnect client profiles.
* Create a S3 bucket and upload your Cisco AnyConnect images and AnyConnect profiles to it. Ensure that the files are available for uploading to the cluster. This can be done by serving them over HTTP/HTTPS or syncing them to an S3 bucket. The following example shows the S3 bucket used to provision the cluster.

   aws s3 cp . s3://$BUCKET --recursive --exclude "*" --include "anyconnect-*"
